export const UPDATE_USER_STATE = 'UPDATE_USER_STATE';
export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_FINISH = 'UPDATE_USER_FINISH';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const UPDATE_USER_REMOVE_SUCCESS = 'UPDATE_USER_REMOVE_SUCCESS';
